In [1]:
import tensorflow as tf
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import os
import xlrd

In [2]:
learning_rate=1.0
nn_epochs = 30

In [3]:
Data_file = "heart.xls"

In [5]:
book = xlrd.open_workbook(Data_file, encoding_override="UTF-8")
sheet = book.sheet_by_index(0)
print (sheet)
for i in range(463):
    if sheet.cell_value(i, 4) == "Present":
        sheet._cell_values[i][4] = 1.0
    else:
        sheet._cell_values[i][4] = 0.0

#print(x1)

In [7]:
inp = [[sheet.cell_value(row, col) for col in range(sheet.ncols-1)] for row in range(1, sheet.nrows)]
outp = [[sheet.cell_value(row,9) for row in range(1, sheet.nrows)]]
print(sheet.ncols)
print(sheet.nrows)

10
463


In [64]:
sess = tf.Session()

In [65]:
sess.run(tf.shape(inp))

array([462,   9], dtype=int32)

In [66]:
X=tf.placeholder(tf.float32, [sheet.nrows-1, 9])
Y=tf.placeholder(tf.float32,[1,sheet.nrows-1])

In [67]:
w = tf.Variable(tf.random_normal(shape=[9, 1], stddev=0.01))
b = tf.Variable(tf.random_normal(shape=[sheet.nrows-1, 1], stddev=0.01))           

In [68]:
logits = tf.matmul(X, w) + b

In [69]:
entropy = tf.nn.softmax_cross_entropy_with_logits(logits=tf.reshape(logits, [1, sheet.nrows-1]), labels=outp, name='entropy')
loss = tf.reduce_mean(entropy)

In [70]:
optimizer = tf.train.AdamOptimizer(learning_rate).minimize(loss)

In [71]:
sess = tf.Session()

In [72]:
start_time = time.time()
sess.run(tf.initialize_all_variables())
for i in range(30):
    total_loss = 0
    for _ in range(sheet.nrows-1):
         total_loss = 0
         _, loss_batch = sess.run([optimizer, loss], feed_dict={X: inp, Y: outp})
         total_loss += loss_batch
print ('Average loss epoch {0}: {1}'.format(i, total_loss))
print('Optimization Finished!')

Average loss epoch 29: 287224864.0
Optimization Finished!


In [73]:
Data_file = "heart.xls" 

In [74]:
tbook = xlrd.open_workbook(Data_file, encoding_override='utf-8')
tsheet = book.sheet_by_index(0)
tinp = [[sheet.cell_value(r, c) for c in range(sheet.ncols-1)] for r in range(1, sheet.nrows)]
toutp = [[sheet.cell_value(r,9) for r in range(1, sheet.nrows)]]

In [75]:
sess.run(tf.shape(tinp))

array([462,   9], dtype=int32)

In [76]:
sess.run(tf.shape(toutp))

array([  1, 462], dtype=int32)

In [77]:
sess.run(tf.shape(inp))

array([462,   9], dtype=int32)

In [78]:
sess.run(tf.shape(outp))

array([  1, 462], dtype=int32)

In [80]:

total_correct_preds = 0
#for _ in range(sheet.nrows-1):
    #logic_batch = sess.run(logits, feed_dict={X:tinp, Y:toutp})
_, loss_batch = sess.run([optimizer,logits], feed_dict={X: tinp, Y:toutp})
preds = tf.nn.softmax(loss_batch)
correct_preds = tf.equal(tf.argmax(preds, 1), tf.argmax(toutp, 1))
accuracy = tf.reduce_sum(tf.cast(correct_preds, tf.float32))
total_correct_preds+=sess.run(accuracy) 
print('Accuracy{0}'.format(total_correct_preds/sheet.nrows))

Accuracy0.997840172786
